/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.superhumanos.view;
import com.mycompany.superhumanos.control.MenuControl;

/**
 *
 * @author Leonardo.amaris
 */
public class Menu extends javax.swing.JFrame {
    /**
     * Creates new form menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Guerra = new javax.swing.JButton();
        LlegadaAlFis = new javax.swing.JButton();
        MostrarAlFIs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Admitidos = new javax.swing.JButton();
        Rechazados = new javax.swing.JButton();
        FormarEscuadrones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Guerra.setText("Guerra");
        Guerra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuerraActionPerformed(evt);
            }
        });

        LlegadaAlFis.setText("Llegada");
        LlegadaAlFis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LlegadaAlFisActionPerformed(evt);
            }
        });

        MostrarAlFIs.setText("Mostrar");
        MostrarAlFIs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarAlFIsActionPerformed(evt);
            }
        });

        jLabel2.setText("Llegada de AlFIs");

        Admitidos.setText("Admitidos");
        Admitidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmitidosActionPerformed(evt);
            }
        });

        Rechazados.setText("Rechazados");
        Rechazados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechazadosActionPerformed(evt);
            }
        });

        FormarEscuadrones.setText("Escuadrones");
        FormarEscuadrones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormarEscuadronesActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Grupo de SuperHumanos");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Admitidos)
                        .addGap(18, 18, 18)
                        .addComponent(Rechazados)
                        .addGap(18, 18, 18)
                        .addComponent(FormarEscuadrones))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Guerra, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(LlegadaAlFis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(MostrarAlFIs, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Agregar))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admitidos)
                    .addComponent(Rechazados)
                    .addComponent(FormarEscuadrones))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LlegadaAlFis)
                    .addComponent(MostrarAlFIs))
                .addGap(34, 34, 34)
                .addComponent(Guerra)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuerraActionPerformed
        MenuControl.GuerraAction();
    }//GEN-LAST:event_GuerraActionPerformed

    private void RechazadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechazadosActionPerformed
        MenuControl.RechazadosAction();
    }//GEN-LAST:event_RechazadosActionPerformed

    private void FormarEscuadronesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormarEscuadronesActionPerformed
        MenuControl.FormarEscuadronesAction();
    }//GEN-LAST:event_FormarEscuadronesActionPerformed

    private void AdmitidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmitidosActionPerformed
        MenuControl.AdmitidosAction();
    }//GEN-LAST:event_AdmitidosActionPerformed

    private void LlegadaAlFisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LlegadaAlFisActionPerformed
        MenuControl.LlegadaAlFisAction();
    }//GEN-LAST:event_LlegadaAlFisActionPerformed

    private void MostrarAlFIsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarAlFIsActionPerformed
        MenuControl.MostrarAlFIsAction();
    }//GEN-LAST:event_MostrarAlFIsActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        MenuControl.AgregarAction();
    }//GEN-LAST:event_AgregarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admitidos;
    private javax.swing.JButton Agregar;
    private javax.swing.JButton FormarEscuadrones;
    private javax.swing.JButton Guerra;
    private javax.swing.JButton LlegadaAlFis;
    private javax.swing.JButton MostrarAlFIs;
    private javax.swing.JButton Rechazados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
